# Generated by Django 4.0.4 on 2022-06-21 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='maquinaria',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='usuario',
        ),
    ]
